version: '3'

services:

        highlaravel:
            build:
                context: ./docker/php-fpm
                args:
                    - timezone=${TZ}
            volumes:
                - ./highlaravel:/highlaravel:rw,cached
                - highlaravel_log:/highlaravel/var/log
            env_file:
                - .env
            depends_on:
                - mysql
                - redis
                - memcached
            environment:
                XDEBUG_CONFIG: idekey=PHPSTORM remote_host=${XDEBUG_REMOTE_HOST} remote_port=9000
                PHP_IDE_CONFIG: serverName=${NGINX_HOST}

        nginx:
            build:
                context: ./docker/nginx
                args:
                    - nginx_host=${NGINX_HOST}
            ports:
                - "80:80"
                - "443:443"
            depends_on:
                - highlaravel
            volumes:
                - ./highlaravel/public:/highlaravel/public:ro
                - ./docker/nginx/default.template:/etc/nginx/conf.d/default.template
                - nginx_log:/var/log/nginx
            env_file:
                - .env
            command: /bin/bash -c "envsubst '$$NGINX_HOST'
                < /etc/nginx/conf.d/default.template
                > /etc/nginx/conf.d/default.conf
                && exec nginx -g 'daemon off;'"

        mysql:
            build:
                context: ./docker/db
                dockerfile: Dockerfile.mysql
            volumes:
                - ./.data/mysql:/var/lib/mysql:rw
            env_file:
                - .env
            ports:
                - "3306:3306"

        redis:
            build:
                context: ./docker/redis
        
        memcached:
            image: memcached:alpine
            restart: always

volumes:
    nginx_log:
    highlaravel_log:
